from __future__ import annotations
from typing import Any, Protocol
from ..models import AnalysisResult, SourceSpec

class AnalyzerAdapter(Protocol):
    def analyze(self, source: SourceSpec) -> AnalysisResult: ...

class EditorTransport(Protocol):
    def import_media(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def run_agent(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def wait(self, job_id: str) -> dict[str, Any]: ...
    def get_project(self, project_id: str) -> dict[str, Any]: ...
    def publish(self, payload: dict[str, Any]) -> dict[str, Any]: ...
